<?php

namespace Modules\Role\Repositories;

use App\Repositories\BaseRepository;
use Modules\Role\Models\Role;
use Modules\Role\Repositories\Criteria\RoleRequestCriteria;
use Prettus\Repository\Exceptions\RepositoryException;

class RoleRepository extends BaseRepository
{
    /**
     * {@inheritDoc}
     */
    public function model(): string
    {
        return Role::class;
    }

    /**
     * {@inheritDoc}
     */
    public function boot()
    {
        $this->pushPermissionColumnValidator(RoleColumnPermissionValidator::class);
        $this->pushCriteria(RoleRequestCriteria::class);
    }

    public function all($columns = ['*'])
    {
        return parent::all($columns); // TODO: Change the autogenerated stub
    }

    /**
     * Find by id or throw 404
     *
     * @param    $id
     * @param  array  $columns
     * @return mixed
     *
     * @throws RepositoryException
     */
    public function findOrNull($id, array $columns = ['*']): mixed
    {
        $this->applyCriteria();
        $this->applyScope();
        $model = $this->model->find($id, $columns);
        $this->resetModel();

        return $this->parserResult($model);
    }
}
