image: php:8.1-fpm

pipelines:
  default:
    - step:
        script:
          - gpg --recv-key 0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c && gpg --export 0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c > /usr/share/keyrings/ppa_ondrej_php.gpg
          -  echo "deb [signed-by=/usr/share/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ppa_ondrej_php.list
          - apt-get update && apt-get install -qy git curl libmcrypt-dev libzip-dev libpng-dev php8.1-curl php8.1-redis php8.1-zip
          - docker-php-ext-install exif pcntl gd pgsql pdo_pgsql 
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan migrate --seed
          - php artisan serve &
          - sleep 5
          - ./vendor/bin/phpunit
          - curl -vk http://localhost:8000
        services:
          - pgsql
          - redis

definitions:
  services:
    redis:
      image: redis
    pgsql:
      image: postgres
      environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
