version: '3'
services:
    app:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
        image: php:8.1
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - app
        depends_on:
            - pgsql
            - redis

    pgsql:
        image: 'postgres:14'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql-volume:/var/lib/postgresql/data'
        networks:
            - app
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis-volume:/data'
        networks:
            - app
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]

networks:
    app:
        driver: bridge
volumes:
    pgsql-volume:
        driver: local
    redis-volume:
        driver: local
