<?php

namespace Modules\Worker\Http\Resources;

use App\Http\Resources\BaseJsonResource;

class WorkerResource extends BaseJsonResource
{
    public function toArray($request): array
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
